export const GAME_STARTED = "GAME_STARTED";
export const SET_COLUMN_SIZE = "SET_COLUMN_SIZE";
export const CREATE_BOARD_STATUS = "CREATE_BOARD_STATUS";
export const PLAYER_CLICKED_CELL = "PLAYER_CLICKED_CELL";
export const SET_SUCCESS_CONDITION_MAP = "SET_SUCCESS_CONDITION_MAP";
export const END_GAME_AND_SET_WINNER = "END_GAME_AND_SET_WINNER";
